import type { TowerConfig } from "./types.js";

export const TOWER_CONFIGS: Record<string, TowerConfig> = {
  arrow: {
    kind: "arrow",
    name: "Arrow Tower",
    cost: 50,
    damage: 10,
    range: 3,
    fireRate: 2,
    splash: 0,
    special: null,
    upgrades: [
      { tier: 1, cost: 40, damageMultiplier: 1.5, rangeMultiplier: 1, fireRateMultiplier: 1.2, specialization: null },
      { tier: 2, cost: 80, damageMultiplier: 2, rangeMultiplier: 1.2, fireRateMultiplier: 1.4, specialization: null },
      { tier: 3, cost: 160, damageMultiplier: 3, rangeMultiplier: 1.5, fireRateMultiplier: 1.6, specialization: "Sniper" },
    ],
  },
  cannon: {
    kind: "cannon",
    name: "Cannon Tower",
    cost: 80,
    damage: 30,
    range: 2,
    fireRate: 0.8,
    splash: 1.5,
    special: "Splash damage",
    upgrades: [
      { tier: 1, cost: 60, damageMultiplier: 1.5, rangeMultiplier: 1, fireRateMultiplier: 1.1, specialization: null },
      { tier: 2, cost: 120, damageMultiplier: 2, rangeMultiplier: 1.1, fireRateMultiplier: 1.2, specialization: null },
      { tier: 3, cost: 240, damageMultiplier: 3, rangeMultiplier: 1.2, fireRateMultiplier: 1.3, specialization: "Siege Cannon" },
    ],
  },
  frost: {
    kind: "frost",
    name: "Frost Tower",
    cost: 60,
    damage: 5,
    range: 3,
    fireRate: 1.5,
    splash: 0,
    special: "Slows enemies",
    upgrades: [
      { tier: 1, cost: 50, damageMultiplier: 1.5, rangeMultiplier: 1.1, fireRateMultiplier: 1.2, specialization: null },
      { tier: 2, cost: 100, damageMultiplier: 2, rangeMultiplier: 1.2, fireRateMultiplier: 1.4, specialization: null },
      { tier: 3, cost: 200, damageMultiplier: 2.5, rangeMultiplier: 1.3, fireRateMultiplier: 1.6, specialization: "Blizzard" },
    ],
  },
  lightning: {
    kind: "lightning",
    name: "Lightning Tower",
    cost: 100,
    damage: 15,
    range: 4,
    fireRate: 1,
    splash: 0,
    special: "Chain to 3 targets",
    upgrades: [
      { tier: 1, cost: 70, damageMultiplier: 1.5, rangeMultiplier: 1, fireRateMultiplier: 1.2, specialization: null },
      { tier: 2, cost: 140, damageMultiplier: 2, rangeMultiplier: 1.2, fireRateMultiplier: 1.3, specialization: null },
      { tier: 3, cost: 280, damageMultiplier: 3, rangeMultiplier: 1.4, fireRateMultiplier: 1.5, specialization: "Tesla Coil" },
    ],
  },
  mortar: {
    kind: "mortar",
    name: "Mortar Tower",
    cost: 120,
    damage: 40,
    range: 5,
    fireRate: 0.4,
    splash: 2,
    special: "Area denial zone",
    upgrades: [
      { tier: 1, cost: 80, damageMultiplier: 1.5, rangeMultiplier: 1, fireRateMultiplier: 1.2, specialization: null },
      { tier: 2, cost: 160, damageMultiplier: 2, rangeMultiplier: 1.1, fireRateMultiplier: 1.3, specialization: null },
      { tier: 3, cost: 320, damageMultiplier: 3, rangeMultiplier: 1.2, fireRateMultiplier: 1.4, specialization: "Napalm Strike" },
    ],
  },
};
